### ISSUE TITLE
Unable to compare the debug and release APK

### ISSUE THREAD

**Issue by mahmood199** [theapache64/dex-diff#3]
Exception that I got

Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.base/java.util.Collections$SingletonList.get(Unknown Source)
        at com.github.theapache64.dexdiff.models.FilesResultKt.generatedDirName(FilesResult.kt:174)
        at com.github.theapache64.dexdiff.models.FilesResultKt.createFileResult(FilesResult.kt:47)
        at com.github.theapache64.dexdiff.ui.home.HomeViewModel.init(HomeViewModel.kt:75)
        at com.github.theapache64.dexdiff.ui.home.HomeActivity.onCreate(HomeActivity.kt:30)
        at com.theapache64.cyclone.core.Activity.startActivity(Activity.kt:17)
        at com.github.theapache64.dexdiff.ui.splash.SplashActivity.access$startActivity(SplashActivity.kt:11)
        at com.github.theapache64.dexdiff.ui.splash.SplashActivity$onCreate$1$1.invoke(SplashActivity.kt:30)
        at com.github.theapache64.dexdiff.ui.splash.SplashActivity$onCreate$1$1.invoke(SplashActivity.kt:28)
        at com.theapache64.cyclone.core.livedata.LiveData.observe(LiveData.kt:36)
        at com.github.theapache64.dexdiff.ui.splash.SplashActivity.onCreate(SplashActivity.kt:28)
        at com.theapache64.cyclone.core.Application.startActivity(Application.kt:11)
        at com.github.theapache64.dexdiff.app.App.onCreate(App.kt:24)
        at com.github.theapache64.dexdiff.app.AppKt.main(App.kt:34)

Steps to reproduce
1. Generate debug and release apk of the same project. zDebug apk named as apk-debug-1 and release apk was named as app-release.apk
2. Move the apks to the root directory of the android project.
3. Now run the command of comparision

**Comment by theapache64** [comment]
Comparing debug and release is not supported at the moment; I am curious why you would want to do that.

**Comment by theapache64** [comment]
Closing due to inactivity. Feel free to reopen
